// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: pb/book/book-create.proto

package book

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookId      string        `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Title       string        `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author      string        `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Publisher   string        `protobuf:"bytes,4,opt,name=publisher,proto3" json:"publisher,omitempty"`
	PagesTotal  int64         `protobuf:"varint,5,opt,name=pages_total,json=pagesTotal,proto3" json:"pages_total,omitempty"`
	Qty         int64         `protobuf:"varint,6,opt,name=qty,proto3" json:"qty,omitempty"`
	Cover       string        `protobuf:"bytes,7,opt,name=cover,proto3" json:"cover,omitempty"`
	Description string        `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	LocationId  string        `protobuf:"bytes,9,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Uploader    *BookUploader `protobuf:"bytes,10,opt,name=uploader,proto3" json:"uploader,omitempty"`
	Editors     []*BookEditor `protobuf:"bytes,11,rep,name=editors,proto3" json:"editors,omitempty"`
}

func (x *BookCreateRequest) Reset() {
	*x = BookCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_book_book_create_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookCreateRequest) ProtoMessage() {}

func (x *BookCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_book_book_create_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookCreateRequest.ProtoReflect.Descriptor instead.
func (*BookCreateRequest) Descriptor() ([]byte, []int) {
	return file_pb_book_book_create_proto_rawDescGZIP(), []int{0}
}

func (x *BookCreateRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *BookCreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookCreateRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BookCreateRequest) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *BookCreateRequest) GetPagesTotal() int64 {
	if x != nil {
		return x.PagesTotal
	}
	return 0
}

func (x *BookCreateRequest) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *BookCreateRequest) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *BookCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BookCreateRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *BookCreateRequest) GetUploader() *BookUploader {
	if x != nil {
		return x.Uploader
	}
	return nil
}

func (x *BookCreateRequest) GetEditors() []*BookEditor {
	if x != nil {
		return x.Editors
	}
	return nil
}

type BookCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BookCreateResponse) Reset() {
	*x = BookCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_book_book_create_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookCreateResponse) ProtoMessage() {}

func (x *BookCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_book_book_create_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookCreateResponse.ProtoReflect.Descriptor instead.
func (*BookCreateResponse) Descriptor() ([]byte, []int) {
	return file_pb_book_book_create_proto_rawDescGZIP(), []int{1}
}

var File_pb_book_book_create_proto protoreflect.FileDescriptor

var file_pb_book_book_create_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x62, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x2d, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x70, 0x62, 0x2f,
	0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x2d, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x70, 0x62, 0x2f, 0x62, 0x6f, 0x6f,
	0x6b, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x2d, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xd6, 0x02, 0x0a, 0x11, 0x42, 0x6f, 0x6f, 0x6b, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6f, 0x6f,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x12, 0x1f,
	0x0a, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x73, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x10, 0x0a, 0x03, 0x71, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x71, 0x74,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x08, 0x75, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42,
	0x6f, 0x6f, 0x6b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x52, 0x08, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x07, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x73,
	0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x45, 0x64, 0x69,
	0x74, 0x6f, 0x72, 0x52, 0x07, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x14, 0x0a, 0x12,
	0x42, 0x6f, 0x6f, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x70, 0x62, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_book_book_create_proto_rawDescOnce sync.Once
	file_pb_book_book_create_proto_rawDescData = file_pb_book_book_create_proto_rawDesc
)

func file_pb_book_book_create_proto_rawDescGZIP() []byte {
	file_pb_book_book_create_proto_rawDescOnce.Do(func() {
		file_pb_book_book_create_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_book_book_create_proto_rawDescData)
	})
	return file_pb_book_book_create_proto_rawDescData
}

var file_pb_book_book_create_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_book_book_create_proto_goTypes = []interface{}{
	(*BookCreateRequest)(nil),  // 0: BookCreateRequest
	(*BookCreateResponse)(nil), // 1: BookCreateResponse
	(*BookUploader)(nil),       // 2: BookUploader
	(*BookEditor)(nil),         // 3: BookEditor
}
var file_pb_book_book_create_proto_depIdxs = []int32{
	2, // 0: BookCreateRequest.uploader:type_name -> BookUploader
	3, // 1: BookCreateRequest.editors:type_name -> BookEditor
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_book_book_create_proto_init() }
func file_pb_book_book_create_proto_init() {
	if File_pb_book_book_create_proto != nil {
		return
	}
	file_pb_book_book_uploader_proto_init()
	file_pb_book_book_editor_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_book_book_create_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_book_book_create_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_book_book_create_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_book_book_create_proto_goTypes,
		DependencyIndexes: file_pb_book_book_create_proto_depIdxs,
		MessageInfos:      file_pb_book_book_create_proto_msgTypes,
	}.Build()
	File_pb_book_book_create_proto = out.File
	file_pb_book_book_create_proto_rawDesc = nil
	file_pb_book_book_create_proto_goTypes = nil
	file_pb_book_book_create_proto_depIdxs = nil
}
