// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: pb/book/book-uploader.proto

package book

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookUploader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	User   string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *BookUploader) Reset() {
	*x = BookUploader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_book_book_uploader_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookUploader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookUploader) ProtoMessage() {}

func (x *BookUploader) ProtoReflect() protoreflect.Message {
	mi := &file_pb_book_book_uploader_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookUploader.ProtoReflect.Descriptor instead.
func (*BookUploader) Descriptor() ([]byte, []int) {
	return file_pb_book_book_uploader_proto_rawDescGZIP(), []int{0}
}

func (x *BookUploader) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BookUploader) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

var File_pb_book_book_uploader_proto protoreflect.FileDescriptor

var file_pb_book_book_uploader_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x62, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x2d, 0x75,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a,
	0x0c, 0x42, 0x6f, 0x6f, 0x6b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f,
	0x62, 0x6f, 0x6f, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_book_book_uploader_proto_rawDescOnce sync.Once
	file_pb_book_book_uploader_proto_rawDescData = file_pb_book_book_uploader_proto_rawDesc
)

func file_pb_book_book_uploader_proto_rawDescGZIP() []byte {
	file_pb_book_book_uploader_proto_rawDescOnce.Do(func() {
		file_pb_book_book_uploader_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_book_book_uploader_proto_rawDescData)
	})
	return file_pb_book_book_uploader_proto_rawDescData
}

var file_pb_book_book_uploader_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_book_book_uploader_proto_goTypes = []interface{}{
	(*BookUploader)(nil), // 0: BookUploader
}
var file_pb_book_book_uploader_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_book_book_uploader_proto_init() }
func file_pb_book_book_uploader_proto_init() {
	if File_pb_book_book_uploader_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_book_book_uploader_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookUploader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_book_book_uploader_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_book_book_uploader_proto_goTypes,
		DependencyIndexes: file_pb_book_book_uploader_proto_depIdxs,
		MessageInfos:      file_pb_book_book_uploader_proto_msgTypes,
	}.Build()
	File_pb_book_book_uploader_proto = out.File
	file_pb_book_book_uploader_proto_rawDesc = nil
	file_pb_book_book_uploader_proto_goTypes = nil
	file_pb_book_book_uploader_proto_depIdxs = nil
}
